// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ2YfPHlbTIQqvbAg7L223EtBCMzyLDf0',
    appId: '1:1043081027798:web:8929b116fdd4aaae842977',
    messagingSenderId: '1043081027798',
    projectId: 'chat-app-5233b',
    authDomain: 'chat-app-5233b.firebaseapp.com',
    storageBucket: 'chat-app-5233b.appspot.com',
    measurementId: 'G-HJ57QS8FQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxt5keOUvD9liAM-YRmKM1WpKhsjrsgUM',
    appId: '1:1043081027798:android:e22a0d1706997707842977',
    messagingSenderId: '1043081027798',
    projectId: 'chat-app-5233b',
    storageBucket: 'chat-app-5233b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaEmyVryCBryB57jG_B3TZYrFg769iCU',
    appId: '1:1043081027798:ios:1ff19f3319e290f1842977',
    messagingSenderId: '1043081027798',
    projectId: 'chat-app-5233b',
    storageBucket: 'chat-app-5233b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaEmyVryCBryB57jG_B3TZYrFg769iCU',
    appId: '1:1043081027798:ios:1ff19f3319e290f1842977',
    messagingSenderId: '1043081027798',
    projectId: 'chat-app-5233b',
    storageBucket: 'chat-app-5233b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ2YfPHlbTIQqvbAg7L223EtBCMzyLDf0',
    appId: '1:1043081027798:web:064526f268ace2e4842977',
    messagingSenderId: '1043081027798',
    projectId: 'chat-app-5233b',
    authDomain: 'chat-app-5233b.firebaseapp.com',
    storageBucket: 'chat-app-5233b.appspot.com',
    measurementId: 'G-8ZJGWRW2QR',
  );

}